import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import GoTop from "./components/GoTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <div id="home" className=" h-screen max-sm:h-svh bg-[url('/bg.svg')]">
          <Navbar />
          <main className="">{children}</main>
          <GoTop />
        </div>
      </body>
    </html>
  );
}
